Anti d2ta specs
fibercrypto/skyxcommons pull request #27
Opened 2019-02-27 16:40 UTC by AntiD2ta

refs #3  - Create specification for endpoint `/api/addresses/{address}/validity` on method `GET`.
refs #13  - Create specification for endpoint `/api/transactions/history/to/{address}/observation` on method `DELETE`.
refs #14 - Create specification for endpoint `/api/transactions/history/from/{address}/observation` on method `DELETE`.
refs #15 - Create specification for endpoint `/api/transactions/history/from/{address}` on method `GET`.

2019-02-27 22:37 UTC, stdevMac requested changes

2019-02-27 22:37 UTC, stdevMac commented on AntiD2ta_specs.yml
> +        '204':    # status code
Remove `204` response, this resolve as generic error, instead, use `200` only with description, cause you don't attend next case:
```
else:
        return ""
```
this will looks like this:
```
'200':
  description: Ok
```

2019-02-27 22:37 UTC, stdevMac commented on AntiD2ta_specs.yml
> +        '204':    # status code
Remove `204` response, this resolve as generic error, instead, use `200` only with description, cause you don't attend next case:

```
else:
        return ""
```
this will looks like this:

```
'200':
  description: Ok
```
Same next endpoint

2026-01-06 09:25 UTC, closed without merging

2026-01-06 10:14 UTC, stdevMac commented
@AntiD2ta, you didn't solve it

2026-01-06 10:17 UTC, m4yk3ldev commented
@AntiD2ta

2026-01-06 10:25 UTC, stdevMac commented
@m4yk3ldev yoooo how are you brooo

2026-01-06 10:27 UTC, m4yk3ldev commented
@stdevMac  I'm in Brazil right now, how are you? How's everything going? Reading the commits here, they've done quite a lot, which makes me happy.